<?php

namespace Database\Seeders;

use App\Models\QuestionBankItem;
use App\Models\QuestionCategory;
use App\Models\User;
use Illuminate\Database\Seeder;

class QuestionBankSampleSeeder extends Seeder
{
    public function run(): void
    {
        $creatorId = User::where('role', 'teacher')->value('id') ?: User::value('id');

        $categories = [];
        foreach ($this->categorySeedData() as $key => $data) {
            $categories[$key] = QuestionCategory::updateOrCreate(
                [
                    'name' => $data['name'],
                    'grade_level' => $data['grade_level'],
                    'skill_type' => $data['skill_type'],
                    'topic' => $data['topic'],
                ],
                [
                    'is_active' => true,
                ]
            );
        }

        foreach ($this->questionSeedData() as $questionData) {
            $category = $categories[$questionData['category_key']];

            $item = QuestionBankItem::updateOrCreate(
                [
                    'category_id' => $category->id,
                    'question_text' => $questionData['question_text'],
                ],
                [
                    'title' => $questionData['title'],
                    'passage' => $questionData['passage'],
                    'audio_url' => $questionData['audio_url'],
                    'answer_mode' => $questionData['answer_mode'],
                    'interaction_type' => $questionData['interaction_type'] ?? 'normal',
                    'interaction_data' => $questionData['interaction_data'] ?? null,
                    'context_type' => $questionData['context_type'],
                    'difficulty' => $questionData['difficulty'],
                    'correct_answer' => $questionData['correct_answer'],
                    'explanation' => $questionData['explanation'],
                    'is_active' => true,
                    'created_by' => $creatorId,
                ]
            );

            $item->options()->delete();

            if ($questionData['answer_mode'] === 'select') {
                foreach ($questionData['options'] as $index => $option) {
                    $item->options()->create([
                        'option_text' => $option['text'],
                        'is_correct' => $option['is_correct'],
                        'order_index' => $index + 1,
                    ]);
                }
            }
        }

        if ($this->command) {
            $this->command->info('Question bank sample data seeded successfully.');
            $this->command->table(
                ['Type', 'Count'],
                [
                    ['Question categories', QuestionCategory::count()],
                    ['Question bank items', QuestionBankItem::count()],
                ]
            );
        }
    }

    private function categorySeedData(): array
    {
        return [
            'g6_vocab_school' => [
                'name' => 'Tu vung do dung hoc tap',
                'grade_level' => 6,
                'skill_type' => 'vocabulary',
                'topic' => 'Truong hoc',
            ],
            'g6_grammar_daily' => [
                'name' => 'Thi hien tai don',
                'grade_level' => 6,
                'skill_type' => 'grammar',
                'topic' => 'Sinh hoat hang ngay',
            ],
            'g6_listening_directions' => [
                'name' => 'Nghe chi duong',
                'grade_level' => 6,
                'skill_type' => 'listening',
                'topic' => 'Chi duong',
            ],
            'g6_speaking_greetings' => [
                'name' => 'Noi chao hoi ban be',
                'grade_level' => 6,
                'skill_type' => 'speaking',
                'topic' => 'Giao tiep hang ngay',
            ],
            'g6_reading_school' => [
                'name' => 'Doc hieu truong hoc',
                'grade_level' => 6,
                'skill_type' => 'reading',
                'topic' => 'Truong hoc',
            ],
            'g6_writing_routine' => [
                'name' => 'Viet ve lich trinh hang ngay',
                'grade_level' => 6,
                'skill_type' => 'writing',
                'topic' => 'Sinh hoat hang ngay',
            ],
            'g7_reading_hobbies' => [
                'name' => 'Doc hieu ve so thich',
                'grade_level' => 7,
                'skill_type' => 'reading',
                'topic' => 'So thich',
            ],
            'g7_listening_directions' => [
                'name' => 'Nghe chi duong',
                'grade_level' => 7,
                'skill_type' => 'listening',
                'topic' => 'Chi duong',
            ],
            'g8_writing_weekend' => [
                'name' => 'Viet ve cuoi tuan truoc',
                'grade_level' => 8,
                'skill_type' => 'writing',
                'topic' => 'Cuoi tuan',
            ],
            'g8_reading_environment' => [
                'name' => 'Doc hieu moi truong',
                'grade_level' => 8,
                'skill_type' => 'reading',
                'topic' => 'Moi truong',
            ],
            'g9_grammar_passive' => [
                'name' => 'Cau bi dong',
                'grade_level' => 9,
                'skill_type' => 'grammar',
                'topic' => 'Cau truc ngu phap',
            ],
            'g9_listening_travel' => [
                'name' => 'Nghe hoi thoai du lich',
                'grade_level' => 9,
                'skill_type' => 'listening',
                'topic' => 'Du lich',
            ],
        ];
    }

    private function questionSeedData(): array
    {
        return [
            [
                'category_key' => 'g6_vocab_school',
                'title' => 'School things 1',
                'question_text' => 'Which word means "cuc tay"?',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => '"Eraser" la tu chi cuc tay.',
                'options' => [
                    ['text' => 'Eraser', 'is_correct' => true],
                    ['text' => 'Notebook', 'is_correct' => false],
                    ['text' => 'Ruler', 'is_correct' => false],
                    ['text' => 'School bag', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_vocab_school',
                'title' => 'School things 2',
                'question_text' => 'Write the English word for "bang".',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'blackboard',
                'explanation' => 'Cau tra loi mau la "blackboard".',
                'options' => [],
            ],
            [
                'category_key' => 'g6_vocab_school',
                'title' => 'School things 3',
                'question_text' => 'Choose the correct word: I put my books in my ___.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Sach thuong duoc de trong cap.',
                'options' => [
                    ['text' => 'backpack', 'is_correct' => true],
                    ['text' => 'pencil', 'is_correct' => false],
                    ['text' => 'eraser', 'is_correct' => false],
                    ['text' => 'clock', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 1',
                'question_text' => 'Lan ___ to school at 6:30 every morning.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Chu ngu so it o hien tai don dung dong tu them "-es".',
                'options' => [
                    ['text' => 'go', 'is_correct' => false],
                    ['text' => 'goes', 'is_correct' => true],
                    ['text' => 'going', 'is_correct' => false],
                    ['text' => 'went', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 2',
                'question_text' => 'Complete the sentence: They ___ soccer after school every day.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'play',
                'explanation' => 'Voi chu ngu "They", dung dong tu nguyen mau "play".',
                'options' => [],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 3',
                'question_text' => 'Which sentence is correct?',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Chu ngu "He" dung dong tu them "-es".',
                'options' => [
                    ['text' => 'He brush his teeth every night.', 'is_correct' => false],
                    ['text' => 'He brushes his teeth every night.', 'is_correct' => true],
                    ['text' => 'He brushed his teeth every night.', 'is_correct' => false],
                    ['text' => 'He brushing his teeth every night.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 4',
                'question_text' => 'Choose the correct form: My brother ___ TV after dinner.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Chu ngu so it nen dung dong tu them "-es": watches.',
                'options' => [
                    ['text' => 'watch', 'is_correct' => false],
                    ['text' => 'watches', 'is_correct' => true],
                    ['text' => 'watching', 'is_correct' => false],
                    ['text' => 'watched', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 5',
                'question_text' => 'Fill in the blank: She ___ her homework every evening. (do)',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'does',
                'explanation' => 'Voi "she", dong tu "do" doi thanh "does".',
                'options' => [],
            ],
            [
                'category_key' => 'g6_grammar_daily',
                'title' => 'Present simple 6',
                'question_text' => 'Which adverb is often used with the present simple tense?',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => '"Usually" la trang tu tan suat thuong dung voi hien tai don.',
                'options' => [
                    ['text' => 'Yesterday', 'is_correct' => false],
                    ['text' => 'Usually', 'is_correct' => true],
                    ['text' => 'Tomorrow', 'is_correct' => false],
                    ['text' => 'Last night', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_listening_directions',
                'title' => 'Listening directions 3',
                'question_text' => 'What does the speaker ask you to do first in the audio?',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g6-directions-first-step.mp3',
                'answer_mode' => 'select',
                'context_type' => 'listening',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Nghe file va chon huong dan duoc de dau tien.',
                'options' => [
                    ['text' => 'Turn left at the school gate.', 'is_correct' => true],
                    ['text' => 'Go straight to the park.', 'is_correct' => false],
                    ['text' => 'Cross the street at the zebra crossing.', 'is_correct' => false],
                    ['text' => 'Wait for the bus.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_listening_directions',
                'title' => 'Listening directions 4',
                'question_text' => 'Write the place the speaker says you should visit after the library.',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g6-directions-next-place.mp3',
                'answer_mode' => 'input',
                'context_type' => 'listening',
                'difficulty' => 'medium',
                'correct_answer' => 'museum',
                'explanation' => 'Sau thu vien, nguoi noi chuyen noi den bao tang.',
                'options' => [],
            ],
            [
                'category_key' => 'g6_speaking_greetings',
                'title' => 'Speaking greetings 1',
                'question_text' => 'Match each greeting with the best response.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Noi qui tac thong thuong trong cac cau chao hoi.',
                'options' => [],
                'interaction_type' => 'matching',
                'interaction_data' => [
                    'pairs' => [
                        ['left' => 'Good morning!', 'right_type' => 'text', 'right' => 'Good morning!'],
                        ['left' => 'How are you?', 'right_type' => 'text', 'right' => 'I am fine, thank you.'],
                        ['left' => 'See you later.', 'right_type' => 'text', 'right' => 'Bye, see you soon.'],
                    ],
                ],
            ],
            [
                'category_key' => 'g6_speaking_greetings',
                'title' => 'Speaking greetings 2',
                'question_text' => 'How do you say "Chao buoi sang" in English?',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'good morning',
                'explanation' => 'Dap an la "Good morning".',
                'options' => [],
            ],
            [
                'category_key' => 'g6_reading_school',
                'title' => 'Reading school 1',
                'question_text' => 'Match each school subject with the correct activity.',
                'passage' => 'School is fun. Students study maths, music, and art. They solve problems in maths, sing songs in music, and draw pictures in art.',
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'reading',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Noi dung chinh la hoat dong phu hop voi tung mon hoc.',
                'options' => [],
                'interaction_type' => 'matching',
                'interaction_data' => [
                    'pairs' => [
                        ['left' => 'Maths', 'right_type' => 'text', 'right' => 'Solve problems'],
                        ['left' => 'Music', 'right_type' => 'text', 'right' => 'Sing songs'],
                        ['left' => 'Art', 'right_type' => 'text', 'right' => 'Draw pictures'],
                    ],
                ],
            ],
            [
                'category_key' => 'g6_writing_routine',
                'title' => 'Writing routine 1',
                'question_text' => 'Put the words in the correct order to make a sentence.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Cau dung theo thu tu tu ban dau den cuoi.',
                'options' => [],
                'interaction_type' => 'ordering',
                'interaction_data' => [
                    'items' => [
                        'after school',
                        'my homework',
                        'I do',
                        'every day',
                    ],
                ],
            ],
            [
                'category_key' => 'g6_writing_routine',
                'title' => 'Writing routine 2',
                'question_text' => 'Write one sentence about what you do before bedtime.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'medium',
                'correct_answer' => 'I brush my teeth before bedtime.',
                'explanation' => 'Dap an mau la mot cau don.',
                'options' => [],
            ],
            [
                'category_key' => 'g6_vocab_school',
                'title' => 'School things 4',
                'question_text' => 'Which item do you use to cut paper?',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => null,
                'explanation' => 'Scissors la dung cu dung de cat giay.',
                'options' => [
                    ['text' => 'Glue', 'is_correct' => false],
                    ['text' => 'Scissors', 'is_correct' => true],
                    ['text' => 'Notebook', 'is_correct' => false],
                    ['text' => 'Compass', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g6_vocab_school',
                'title' => 'School things 5',
                'question_text' => 'Write the English word for "thuoc ke".',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'ruler',
                'explanation' => 'Dap an mau la "ruler".',
                'options' => [],
            ],
            [
                'category_key' => 'g7_reading_hobbies',
                'title' => 'Reading hobbies 1',
                'question_text' => 'Why does Minh enjoy collecting stamps?',
                'passage' => 'Minh loves collecting stamps in his free time. He has stamps from Vietnam, Japan, and Australia. He says the hobby helps him learn about different countries and famous places.',
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'reading',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Bai doc noi ro so thich nay giup Minh hoc ve cac quoc gia khac nhau.',
                'options' => [
                    ['text' => 'Because it helps him learn about different countries.', 'is_correct' => true],
                    ['text' => 'Because his mother forces him to do it.', 'is_correct' => false],
                    ['text' => 'Because he can sell stamps every weekend.', 'is_correct' => false],
                    ['text' => 'Because he does not like reading books.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g7_reading_hobbies',
                'title' => 'Reading hobbies 2',
                'question_text' => 'What does Mai usually grow in her garden?',
                'passage' => 'Mai spends a lot of time in her small garden behind the house. She waters the plants every afternoon and often grows tomatoes, cucumbers, and some herbs for her family meals.',
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'reading',
                'difficulty' => 'medium',
                'correct_answer' => 'tomatoes, cucumbers, and herbs',
                'explanation' => 'Co the cham linh hoat theo y dung, dap an mau gom tomatoes, cucumbers, and herbs.',
                'options' => [],
            ],
            [
                'category_key' => 'g7_listening_directions',
                'title' => 'Listening directions 1',
                'question_text' => 'According to the audio, where should Nam turn first to get to the bookstore?',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g7-directions-turn-left.mp3',
                'answer_mode' => 'select',
                'context_type' => 'listening',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Dap an mau gia dinh trong file nghe la turn left first.',
                'options' => [
                    ['text' => 'Turn left at the traffic lights.', 'is_correct' => true],
                    ['text' => 'Turn right at the bakery.', 'is_correct' => false],
                    ['text' => 'Go straight for two kilometers.', 'is_correct' => false],
                    ['text' => 'Go back to the bus station.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g7_listening_directions',
                'title' => 'Listening directions 2',
                'question_text' => 'What place is next to the bakery in the audio?',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g7-directions-bakery.mp3',
                'answer_mode' => 'input',
                'context_type' => 'listening',
                'difficulty' => 'medium',
                'correct_answer' => 'post office',
                'explanation' => 'Dap an mau la "post office".',
                'options' => [],
            ],
            [
                'category_key' => 'g8_writing_weekend',
                'title' => 'Past simple writing 1',
                'question_text' => 'Write one correct past simple form of the verb "go".',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'went',
                'explanation' => 'Dong tu qua khu cua "go" la "went".',
                'options' => [],
            ],
            [
                'category_key' => 'g8_writing_weekend',
                'title' => 'Past simple writing 2',
                'question_text' => 'Complete the sentence in the past simple: Last Sunday, we ___ football in the park.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'easy',
                'correct_answer' => 'played',
                'explanation' => 'Cau co dau hieu qua khu nen dung "played".',
                'options' => [],
            ],
            [
                'category_key' => 'g8_reading_environment',
                'title' => 'Reading environment 1',
                'question_text' => 'What did the students collect during recycling day?',
                'passage' => 'Every month, Green School holds a recycling day. Students bring old newspapers, plastic bottles, and empty cans from home. The class with the most useful recycled items wins a small prize.',
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'reading',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Bai doc neu ro hoc sinh mang newspapers, plastic bottles, va empty cans.',
                'options' => [
                    ['text' => 'Old newspapers, plastic bottles, and empty cans', 'is_correct' => true],
                    ['text' => 'Only glass bottles and paper bags', 'is_correct' => false],
                    ['text' => 'New books and notebooks', 'is_correct' => false],
                    ['text' => 'Food and clothes', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g8_reading_environment',
                'title' => 'Reading environment 2',
                'question_text' => 'How often does Green School hold recycling day?',
                'passage' => 'Every month, Green School holds a recycling day. Students bring old newspapers, plastic bottles, and empty cans from home. The class with the most useful recycled items wins a small prize.',
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'reading',
                'difficulty' => 'easy',
                'correct_answer' => 'every month',
                'explanation' => 'Tan suat la "every month".',
                'options' => [],
            ],
            [
                'category_key' => 'g9_grammar_passive',
                'title' => 'Passive voice 1',
                'question_text' => 'Choose the correct passive sentence for: People speak English all over the world.',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'select',
                'context_type' => 'normal',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Cau bi dong dung la "English is spoken all over the world."',
                'options' => [
                    ['text' => 'English is spoken all over the world.', 'is_correct' => true],
                    ['text' => 'English speaks all over the world.', 'is_correct' => false],
                    ['text' => 'English was spoken all over the world every day.', 'is_correct' => false],
                    ['text' => 'English is speak all over the world.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g9_grammar_passive',
                'title' => 'Passive voice 2',
                'question_text' => 'Complete the passive sentence: The homework ___ by Lan yesterday. (finish)',
                'passage' => null,
                'audio_url' => null,
                'answer_mode' => 'input',
                'context_type' => 'normal',
                'difficulty' => 'medium',
                'correct_answer' => 'was finished',
                'explanation' => 'Dau hieu qua khu "yesterday" nen dung "was finished".',
                'options' => [],
            ],
            [
                'category_key' => 'g9_listening_travel',
                'title' => 'Listening travel 1',
                'question_text' => 'What time will the bus leave according to the conversation?',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g9-travel-bus-time.mp3',
                'answer_mode' => 'select',
                'context_type' => 'listening',
                'difficulty' => 'medium',
                'correct_answer' => null,
                'explanation' => 'Dap an mau trong file nghe la 7:30 a.m.',
                'options' => [
                    ['text' => 'At 6:45 a.m.', 'is_correct' => false],
                    ['text' => 'At 7:30 a.m.', 'is_correct' => true],
                    ['text' => 'At 8:15 a.m.', 'is_correct' => false],
                    ['text' => 'At 9:00 a.m.', 'is_correct' => false],
                ],
            ],
            [
                'category_key' => 'g9_listening_travel',
                'title' => 'Listening travel 2',
                'question_text' => 'Which city are they planning to visit first?',
                'passage' => null,
                'audio_url' => 'https://example.com/audio/g9-travel-first-city.mp3',
                'answer_mode' => 'input',
                'context_type' => 'listening',
                'difficulty' => 'medium',
                'correct_answer' => 'Da Nang',
                'explanation' => 'Dap an mau la Da Nang.',
                'options' => [],
            ],
        ];
    }
}
